# todo: support prebuilt tvm

set(TVM_BUILD_FROM_SOURCE TRUE)
set(TVM_SOURCE ${CMAKE_SOURCE_DIR}/3rdparty/tvm)

if(DEFINED ENV{TVM_ROOT})
  if(EXISTS $ENV{TVM_ROOT}/cmake/config.cmake)
    set(TVM_SOURCE $ENV{TVM_ROOT})
    message(STATUS "Using TVM_ROOT from environment variable: ${TVM_SOURCE}")
  endif()
endif()

message(STATUS "Using TVM source: ${TVM_SOURCE}")

set(TVM_INCLUDES
  ${TVM_SOURCE}/include
  ${TVM_SOURCE}/src
  ${TVM_SOURCE}/3rdparty/dlpack/include
  ${TVM_SOURCE}/3rdparty/dmlc-core/include
)

if(EXISTS ${TVM_SOURCE}/ffi/include)
  list(APPEND TVM_INCLUDES ${TVM_SOURCE}/ffi/include)
elseif(EXISTS ${TVM_SOURCE}/3rdparty/tvm-ffi/include)
  list(APPEND TVM_INCLUDES ${TVM_SOURCE}/3rdparty/tvm-ffi/include)
endif()

if(EXISTS ${TVM_SOURCE}/3rdparty/tvm-ffi/3rdparty/dlpack/include)
  list(APPEND TVM_INCLUDES ${TVM_SOURCE}/3rdparty/tvm-ffi/3rdparty/dlpack/include)
endif()

# update 3rdparty/tvm/3rdparty/tvm-ffi for adding kDLMACA/kDLMACAHost
set(dlpack_header "${TVM_SOURCE}/3rdparty/tvm-ffi/3rdparty/dlpack/include/dlpack/dlpack.h")
file(READ "${dlpack_header}" FILE_CONTENTS)
if(NOT FILE_CONTENTS MATCHES ".*kDLMACA.*")
  string(REPLACE "} DLDeviceType;" "  kDLMACA = 19,\n  kDLMACAHost = 20,\n} DLDeviceType;" NEW_CONTENTS "${FILE_CONTENTS}")
  file(WRITE "${dlpack_header}" "${NEW_CONTENTS}")
endif()
set(ffi_core_pyi "${TVM_SOURCE}/3rdparty/tvm-ffi/python/tvm_ffi/core.pyi")
file(READ "${ffi_core_pyi}" FILE_CONTENTS)
if(NOT FILE_CONTENTS MATCHES ".*kDLMACA.*")
  string(REPLACE "kDLTrn = 17" "kDLTrn = 17\n    kDLMACA = 19\n    kDLMACAHost = 20" NEW_CONTENTS "${FILE_CONTENTS}")
  file(WRITE "${ffi_core_pyi}" "${NEW_CONTENTS}")
endif()
set(ffi_container_tensor "${TVM_SOURCE}/3rdparty/tvm-ffi/include/tvm/ffi/container/tensor.h")
file(READ "${ffi_container_tensor}" FILE_CONTENTS)
if(NOT FILE_CONTENTS MATCHES ".*kDLMACA.*")
  string(REPLACE "device.device_type == kDLROCMHost;" "device.device_type == kDLROCMHost ||\n         device.device_type == kDLMACA || device.device_type == kDLMACAHost;" NEW_CONTENTS "${FILE_CONTENTS}")
  file(WRITE "${ffi_container_tensor}" "${NEW_CONTENTS}")
endif()
set(ffi_cython_base_pxi "${TVM_SOURCE}/3rdparty/tvm-ffi/python/tvm_ffi/cython/base.pxi")
file(READ "${ffi_cython_base_pxi}" FILE_CONTENTS)
if(NOT FILE_CONTENTS MATCHES ".*kDLMACA.*")
  string(REPLACE "kDLTrn = 18" "kDLTrn = 18\n        kDLMACA = 19\n        kDLMACAHost = 20" NEW_CONTENTS "${FILE_CONTENTS}")
  file(WRITE "${ffi_cython_base_pxi}" "${NEW_CONTENTS}")
endif()
set(ffi_cython_device_pxi "${TVM_SOURCE}/3rdparty/tvm-ffi/python/tvm_ffi/cython/device.pxi")
file(READ "${ffi_cython_device_pxi}" FILE_CONTENTS)
if(NOT FILE_CONTENTS MATCHES ".*kDLMACA.*")
  string(REPLACE "kDLTrn = 17" "kDLTrn = 17\n    kDLMACA = 19\n    kDLMACAHost = 20" NEW_CONTENTS "${FILE_CONTENTS}")
  string(REPLACE "DLDeviceType.kDLTrn: \"trn\"," "DLDeviceType.kDLTrn: \"trn\",\n      DLDeviceType.kDLMACA: \"maca\",\n      DLDeviceType.kDLMACAHost: \"maca_host\"," NEW_CONTENTS "${NEW_CONTENTS}")
  string(REPLACE "\"trn\": DLDeviceType.kDLTrn," "\"trn\": DLDeviceType.kDLTrn,\n        \"maca\": DLDeviceType.kDLMACA," NEW_CONTENTS "${NEW_CONTENTS}")
  file(WRITE "${ffi_cython_device_pxi}" "${NEW_CONTENTS}")
endif()
set(torch_c_dlpack "${TVM_SOURCE}/3rdparty/tvm-ffi/python/tvm_ffi/utils/_build_optional_torch_c_dlpack.py")
file(READ "${torch_c_dlpack}" FILE_CONTENTS)
if (NOT FILE_CONTENTS MATCHES ".*kDLMACA.*")
  string(REPLACE "import torch.utils.cpp_extension" "import torch.utils.cpp_extension\nos.environ.pop(\"CXX\", None)" FILE_CONTENTS "${FILE_CONTENTS}")
  string(REPLACE "ctx.device_type = DLDeviceType::kDLCUDA;" "ctx.device_type = DLDeviceType::kDLMACA;" FILE_CONTENTS "${FILE_CONTENTS}")
  string(REPLACE "return at::Device(DeviceType::MPS, index);" "return at::Device(DeviceType::MPS, index);\n    case DLDeviceType::kDLMACA:\n      return at::Device(DeviceType::CUDA, index);" FILE_CONTENTS "${FILE_CONTENTS}")
  string(REPLACE "if (device_type == kDLCUDA || device_type == kDLROCM) {" "if (device_type == kDLCUDA || device_type == kDLROCM || device_type == kDLMACA) {" FILE_CONTENTS "${FILE_CONTENTS}")
  string(REPLACE "cflags.append(\"-DBUILD_WITH_CUDA\")" "cflags.append(\"-DBUILD_WITH_CUDA\")\n            cflags.append(\"-DUSE_MACA\")" FILE_CONTENTS "${FILE_CONTENTS}")
  file(WRITE "${torch_c_dlpack}" "${FILE_CONTENTS}")
endif()
set(tvm_ffi_cpp_extension "${TVM_SOURCE}/3rdparty/tvm-ffi/python/tvm_ffi/cpp/extension.py")
file(READ "${tvm_ffi_cpp_extension}" FILE_CONTENTS)
if (FILE_CONTENTS MATCHES ".*cudart.*")
  string(REPLACE "            default_ldflags += [\n                \"-L{}\".format(str(Path(_find_cuda_home()) / \"lib64\")),\n                \"-lcudart\",\n            ]\n" "" FILE_CONTENTS "${FILE_CONTENTS}")
  file(WRITE "${tvm_ffi_cpp_extension}" "${FILE_CONTENTS}")
endif()
# update 3rdparty/tvm for adding kDLMACA/kDLMACAHost
set(tvm_device_api_header "${TVM_SOURCE}/include/tvm/runtime/device_api.h")
file(READ "${tvm_device_api_header}" FILE_CONTENTS)
if (NOT FILE_CONTENTS MATCHES ".*kDLMACA.*")
  string(REPLACE "default:" "case kDLMACA:\n      return \"maca\";\n    case kDLMACAHost:\n      return \"maca_host\";\n    default:" NEW_CONTENTS "${FILE_CONTENTS}")
  file(WRITE "${tvm_device_api_header}" "${NEW_CONTENTS}")
endif()
